/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;


import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;

/**
 *
 * @author GARGI GHOSH
 */
public class airlines extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
PreparedStatement pst;
int j;
int c=0;
    /**
     * Creates new form airlines
     */
    public airlines() {
        initComponents();
         try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        String sql2;
        sql2 ="select * from airline";
        stmt=this.con.createStatement();
        rs=stmt.executeQuery(sql2);
        while(rs.next())
        {
           c1.addItem(rs.getString("Airline_Name"));
           c2.addItem(rs.getString("Air_servicename"));
           //c++;
        }
        }
        catch(Exception e)
        {
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bot4 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new rojeru_san.complementos.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c1 = new rojerusan.RSComboMetro();
        c2 = new rojerusan.RSComboMetro();
        show = new rojerusan.RSMaterialButtonCircle();
        bot2 = new rojerusan.RSMaterialButtonCircle();
        panel2 = new java.awt.Panel();
        txt5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        t6 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        t5 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        add = new rojerusan.RSMaterialButtonCircle();
        show2 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bot4.setText("<--");
        bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot4ActionPerformed(evt);
            }
        });
        jPanel1.add(bot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 50));

        rSMaterialButtonCircle2.setText("X");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 70, 40));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline_Name", "Airline_No", "Airport", "Rating", "Total seat"
            }
        ));
        tb1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tb1.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb1.setMinimumSize(new java.awt.Dimension(2147483647, 0));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 780, 300));

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel6.setText("Airlines");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel5.setText("Details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        c1.setBorder(new javax.swing.border.MatteBorder(null));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 230, 40));

        c2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 230, 40));

        show.setBackground(new java.awt.Color(255, 51, 51));
        show.setForeground(new java.awt.Color(0, 0, 0));
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 109, 100, 70));

        bot2.setBackground(new java.awt.Color(255, 51, 51));
        bot2.setForeground(new java.awt.Color(0, 0, 0));
        bot2.setText("Refresh");
        bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot2ActionPerformed(evt);
            }
        });
        jPanel1.add(bot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 109, -1, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 840, 610));

        panel2.setBackground(new java.awt.Color(51, 102, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt5.setBackground(new java.awt.Color(51, 102, 255));
        txt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        panel2.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 250, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 30));

        txt1.setBackground(new java.awt.Color(51, 102, 255));
        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        panel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 250, 40));

        t6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t6.setText("Airline No");
        panel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 40));

        txt2.setBackground(new java.awt.Color(51, 102, 255));
        txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        panel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, 40));

        txt4.setBackground(new java.awt.Color(51, 102, 255));
        txt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        panel2.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 250, 40));

        t5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t5.setText("Airline Name");
        panel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 40));

        t8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t8.setText("Airport");
        panel2.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 40));

        t4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t4.setText("Rating");
        panel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, 40));

        t7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t7.setText("Total Seat");
        panel2.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 110, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, 40));

        txt3.setBackground(new java.awt.Color(51, 102, 255));
        txt3.setColumns(20);
        txt3.setRows(5);
        jScrollPane2.setViewportView(txt3);

        panel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 300, 50));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 520));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 50));

        show2.setBackground(new java.awt.Color(255, 255, 255));
        show2.setForeground(new java.awt.Color(0, 0, 0));
        show2.setText("Delete");
        show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show2ActionPerformed(evt);
            }
        });
        jPanel2.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, 49));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 390, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot4ActionPerformed
        // TODO add your handling code here:
        admin_indexpage obn =  new admin_indexpage();
        this.hide();
        obn.show();
    }//GEN-LAST:event_bot4ActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int rowno=tb1.getSelectedRow();
        TableModel model=tb1.getModel();

        txt1.setText(model.getValueAt(rowno, 0).toString());
        txt2.setText(model.getValueAt(rowno, 1).toString());
        txt3.setText(model.getValueAt(rowno, 2).toString());
        txt4.setText(model.getValueAt(rowno, 3).toString());
        txt5.setText(model.getValueAt(rowno, 4).toString());
        
        

    }//GEN-LAST:event_tb1MouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        try
        {
            String ana,ano,air,ret,to_set;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
            String sql="select * from airline where Airline_Name='"+c1.getSelectedItem()+"' and Air_servicename='"+c2.getSelectedItem()+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            while(rs.next())
            {

                ana=rs.getString("Airline_Name");
                ano=rs.getString("AirLine_No");
                air=rs.getString("Air_servicename");
                ret=rs.getString("Rating");
                to_set=rs.getString("Total_Seat");
                
                String arr[]={ ana,ano,air,ret,to_set};
                DefaultTableModel ob=(DefaultTableModel)tb1.getModel();
                ob.addRow(arr);

                //t1.append(ano+"\t");
                //t1.append(fno+"\n");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }

    }//GEN-LAST:event_showActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_show2ActionPerformed

    private void bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel ob=(DefaultTableModel)tb1.getModel();
        c=ob.getRowCount();
        //System.out.print(c);
        for(int i=c-1;i>=0;i--)
        ob.removeRow(i);
    }//GEN-LAST:event_bot2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         try
        {
       String ana,ano,air,ret,to_set;
        
      Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
                ana=txt1.getText();
                ano=txt2.getText();
                air=txt3.getText();
                ret=txt4.getText();
                to_set=txt5.getText();
               int i=0;
      String sql="insert into airline(Airline_Name,AirLine_No,Air_servicename,Rating,Total_Seat) values('"+ana+"','"+ano+"','"+air+"','"+ret+"','"+to_set+"')";     
      pst=this.con.prepareStatement(sql);
      i=pst.executeUpdate();
       if(i==1)
       {
         JOptionPane.showMessageDialog(null, "Inserted Successfully !!!");
        // String arr[]={ana,ano,air,ret,to_set};
         // DefaultTableModel ob=(DefaultTableModel)tb1.getModel();
        // ob.addRow(arr);
       }
      else
          JOptionPane.showMessageDialog(null, "Inserted unSuccessfully !!!");
      

        }
        catch(Exception e)
        {
            System.out.print(e);
        }
                                     

 
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(airlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(airlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(airlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(airlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new airlines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle add;
    private rojerusan.RSMaterialButtonCircle bot2;
    private rojerusan.RSMaterialButtonCircle bot4;
    private rojerusan.RSComboMetro c1;
    private rojerusan.RSComboMetro c2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle show;
    private rojerusan.RSMaterialButtonCircle show2;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private rojeru_san.complementos.RSTableMetro tb1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextArea txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
