/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author GARGI GHOSH
 */
public class customer_flightpage extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
PreparedStatement pst;
String u;
int j;
int c=0;
 
    
    public customer_flightpage() {
        initComponents();
        //t1.set
        p1.setVisible(false);
        t1.setVisible(false); 
        tab1.removeColumn(tab1.getColumnModel().getColumn(8));
        t2.setVisible(false);
   
        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        String sql2;
        sql2 ="select * from flight_airline";
        stmt=this.con.createStatement();
        rs=stmt.executeQuery(sql2);
        while(rs.next())
        {
           c1.addItem(rs.getString("Source"));
           c2.addItem(rs.getString("Destination"));
           //c++;
        }
        }
        catch(Exception e)
        {
        
        }
    
    }
    public customer_flightpage(String una){
        initComponents();
        u=una;
        System.out.print(u);
        l2.setText(u);
    
        p1.setVisible(false);
        t1.setVisible(false); 
        tab1.removeColumn(tab1.getColumnModel().getColumn(8));
        t2.setVisible(false);
        b1.setVisible(false); 

        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        String sql2;
        sql2 ="select * from flight_airline";
        stmt=this.con.createStatement();
        rs=stmt.executeQuery(sql2);
        while(rs.next())
        {
           c1.addItem(rs.getString("Source"));
           c2.addItem(rs.getString("Destination"));
           //c++;
        }
        }
        catch(Exception e)
        {
        
        }
    }
    

    //customer_flightpage(String unm) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c2 = new rojerusan.RSComboMetro();
        c1 = new rojerusan.RSComboMetro();
        ca1 = new com.toedter.calendar.JDateChooser();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new rojeru_san.complementos.RSTableMetro();
        b1 = new rojerusan.RSMaterialButtonRectangle();
        t1 = new javax.swing.JTextField();
        l2 = new rojeru_san.complementos.RSButtonHover();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        bot4 = new rojerusan.RSMaterialButtonCircle();
        bot5 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 231, 40));

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 231, 40));

        ca1.setBackground(new java.awt.Color(51, 102, 255));
        ca1.setForeground(new java.awt.Color(51, 102, 255));
        ca1.setDateFormatString("dd-MM-yy");
        jPanel1.add(ca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 220, 40));

        rSMaterialButtonCircle1.setText("Search");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 150, 50));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight_No", "Source", "Destination", "Departure Date", "Departure time", "Arrival Date", "Arrival time", "Price", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tab1.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tab1.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tab1.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab1.setMinimumSize(new java.awt.Dimension(2147483647, 0));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        b1.setText("BOOK YOUR FLIGHT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 920, 310));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 50, -1));

        l2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, 20));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        bot4.setBackground(new java.awt.Color(51, 102, 255));
        bot4.setForeground(new java.awt.Color(0, 0, 0));
        bot4.setText("<--");
        bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot4ActionPerformed(evt);
            }
        });
        jPanel1.add(bot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        bot5.setBackground(new java.awt.Color(51, 102, 255));
        bot5.setForeground(new java.awt.Color(0, 0, 0));
        bot5.setText("x");
        bot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot5ActionPerformed(evt);
            }
        });
        jPanel1.add(bot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
      
        int rowno=tab1.getSelectedRow();
         TableModel model=tab1.getModel();
        //text10.setVisible(false);
        t1.setText(model.getValueAt(rowno, 8).toString());
        t2.setText(model.getValueAt(rowno,3).toString());
        b1.setVisible(true);
 /*     
        try{
        String fno,src,destn,atym,dtym,price,ddate,adate;
        int id;
         Class.forName("com.mysql.cj.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");

         fno=rs.getString("Flight_No");
         src=rs.getString("Source");
         destn=rs.getString("Destination");
         ddate=rs.getString("Departure_date");
         dtym=rs.getString("Departure_time");
         adate=rs.getString("Arrival_date");
         atym=rs.getString("Arrival_Time");
         price=rs.getString("price");
         id=rs.getInt("ID");
         }
         catch(Exception e)
                 {
                     System.out.print(e);
                 }*/
    }//GEN-LAST:event_tab1MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
    try
     {
       String fno,src,destn,atym,dtym,price,ddate,adate,id;
       
       SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
       String dt1=sdf.format(ca1.getDate());
       Class.forName("com.mysql.cj.jdbc.Driver");
        
        System.out.println(dt1);
       con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
       String sql="select * from flight_airline where Source='"+c1.getSelectedItem()+"' and Destination ='"+c2.getSelectedItem()+"' and Departure_date ='"+dt1+"'";
       stmt=con.createStatement();
       rs=stmt.executeQuery(sql);
       p1.setVisible(true);
       b1.setVisible(false);
       while(rs.next())
       {
           
         
         fno=rs.getString("Flight_No");
         src=rs.getString("Source");
         destn=rs.getString("Destination");
         ddate=rs.getString("Departure_date");
         dtym=rs.getString("Departure_time");
         adate=rs.getString("Arrival_date");
         atym=rs.getString("Arrival_Time");
         price=rs.getString("price");
         id=rs.getString("ID");

         String arr[]={fno,src,destn,ddate,dtym,adate,atym,price,id};
         DefaultTableModel ob=(DefaultTableModel)tab1.getModel();
         ob.addRow(arr);
         
         //t1.append(ano+"\t");
         //t1.append(fno+"\n");
       }
     }
     catch(Exception e)
     {
     System.out.print(e);
     }
      
               // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String x=t1.getText();
        String d=t2.getText();
        this.hide();
        new flight_booking(x,u,d).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot4ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new customer_indexpage(u).setVisible(true);   
    }//GEN-LAST:event_bot4ActionPerformed

    private void bot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bot5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_flightpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_flightpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_flightpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_flightpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_flightpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle b1;
    private rojerusan.RSMaterialButtonCircle bot4;
    private rojerusan.RSMaterialButtonCircle bot5;
    private rojerusan.RSComboMetro c1;
    private rojerusan.RSComboMetro c2;
    private com.toedter.calendar.JDateChooser ca1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSButtonHover l2;
    private javax.swing.JPanel p1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private rojeru_san.complementos.RSTableMetro tab1;
    // End of variables declaration//GEN-END:variables
}
