/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author GARGI GHOSH
 */
public class flight_booking extends javax.swing.JFrame {
 String id;
 Connection con;
 PreparedStatement pst;
 ResultSet rs;
 String f,da;
 int y=1;
 /**
     * Creates new form flight_booking
     */
    public flight_booking() {
        initComponents();
        //tx17.setText(f);

    }
    
public flight_booking(String id,String u,String d) {
      initComponents();
      id=id;
      f=u;
      da=d;
      System.out.print(id);
      System.out.print(f);
      t1.setText(id);
      tx18.setText(da);
      tx17.setText(f);
      tx19.setText(f);
      t1.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        tx1 = new javax.swing.JTextField();
        c3 = new rojerusan.RSComboMetro();
        tx2 = new javax.swing.JTextField();
        c1 = new rojerusan.RSComboMetro();
        c2 = new rojerusan.RSComboMetro();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        tx19 = new javax.swing.JTextField();
        t8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        tx18 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tx5 = new javax.swing.JTextField();
        t11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tx6 = new javax.swing.JTextField();
        t12 = new javax.swing.JLabel();
        tx7 = new javax.swing.JTextField();
        t13 = new javax.swing.JLabel();
        tx8 = new javax.swing.JTextField();
        t14 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        tx9 = new javax.swing.JTextField();
        tx10 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tx11 = new javax.swing.JTextField();
        t16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tx12 = new javax.swing.JTextField();
        t17 = new javax.swing.JLabel();
        tx13 = new javax.swing.JTextField();
        t18 = new javax.swing.JLabel();
        tx14 = new javax.swing.JTextField();
        t19 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        tx15 = new javax.swing.JTextField();
        tx16 = new javax.swing.JTextField();
        t21 = new javax.swing.JLabel();
        bot4 = new rojeru_san.complementos.RSButtonHover();
        jPanel3 = new javax.swing.JPanel();
        tx3 = new javax.swing.JTextField();
        t7 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        tx4 = new javax.swing.JTextField();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        tx17 = new rojeru_san.complementos.RSButtonHover();
        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t2.setText("Class");
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 30));

        t3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t3.setText("User Id");
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 30));

        t4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t4.setText("Gender");
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 70, 30));

        tx1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx1.setForeground(new java.awt.Color(102, 102, 102));
        tx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx1ActionPerformed(evt);
            }
        });
        jPanel2.add(tx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 370, 40));

        c3.setForeground(new java.awt.Color(51, 51, 51));
        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Class", "Business Class", "Economy Class" }));
        jPanel2.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 170, 40));

        tx2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx2.setForeground(new java.awt.Color(102, 102, 102));
        tx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx2ActionPerformed(evt);
            }
        });
        jPanel2.add(tx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 50, 30));

        c1.setForeground(new java.awt.Color(51, 51, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Transgender" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, -1));

        c2.setForeground(new java.awt.Color(51, 51, 51));
        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afghanistan", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "India", "Indonesia" }));
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 210, 40));

        t5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t5.setText("Age");
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 30));

        t6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t6.setText("Country");
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 90, 30));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(204, 204, 204));
        rSMaterialButtonCircle1.setForeground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonCircle1.setText("X");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 50, 40));

        tx19.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        tx19.setForeground(new java.awt.Color(255, 51, 51));
        tx19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx19ActionPerformed(evt);
            }
        });
        jPanel2.add(tx19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, 40));

        t8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t8.setText("Passenger Name");
        jPanel2.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 1020, 200));
        jPanel8.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 40, 30));

        tx18.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx18.setForeground(new java.awt.Color(102, 102, 102));
        tx18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx18ActionPerformed(evt);
            }
        });
        jPanel8.add(tx18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, -1));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("YOUR DESTINATION ADDRESS");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, -1));

        tx5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx5.setForeground(new java.awt.Color(102, 102, 102));
        tx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx5ActionPerformed(evt);
            }
        });
        jPanel4.add(tx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 220, 40));

        t11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t11.setText("City");
        jPanel4.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 60, 30));

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("STATE");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 28, 105, -1));

        jLabel21.setText("POST OFFICE");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 28, 105, -1));

        jLabel22.setText("CITY");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 28, 105, -1));

        jLabel23.setText("YOUR DESTINATION ADDRESS");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 188, -1));

        tx6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx6.setForeground(new java.awt.Color(102, 102, 102));
        tx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx6ActionPerformed(evt);
            }
        });
        jPanel5.add(tx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 50));

        t12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t12.setText("Address");
        jPanel5.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 880, 140));

        tx7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx7.setForeground(new java.awt.Color(102, 102, 102));
        tx7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx7ActionPerformed(evt);
            }
        });
        jPanel4.add(tx7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 60));

        t13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t13.setText("Address");
        jPanel4.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 30));

        tx8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx8.setForeground(new java.awt.Color(102, 102, 102));
        tx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx8ActionPerformed(evt);
            }
        });
        jPanel4.add(tx8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 180, 40));

        t14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t14.setText("State");
        jPanel4.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 60, 30));

        t15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t15.setText("Post Office");
        jPanel4.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 110, 30));

        tx9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx9.setForeground(new java.awt.Color(102, 102, 102));
        tx9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx9ActionPerformed(evt);
            }
        });
        jPanel4.add(tx9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 230, 40));

        tx10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx10.setForeground(new java.awt.Color(102, 102, 102));
        tx10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx10ActionPerformed(evt);
            }
        });
        jPanel4.add(tx10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 40));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("YOUR DESTINATION ADDRESS");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, -1));

        tx11.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx11.setForeground(new java.awt.Color(102, 102, 102));
        tx11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx11ActionPerformed(evt);
            }
        });
        jPanel6.add(tx11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 220, 30));

        t16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t16.setText("City");
        jPanel6.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 60, 30));

        jPanel7.setBackground(new java.awt.Color(51, 102, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("STATE");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 28, 105, -1));

        jLabel26.setText("POST OFFICE");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 28, 105, -1));

        jLabel27.setText("CITY");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 28, 105, -1));

        jLabel28.setText("YOUR DESTINATION ADDRESS");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 188, -1));

        tx12.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx12.setForeground(new java.awt.Color(102, 102, 102));
        tx12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx12ActionPerformed(evt);
            }
        });
        jPanel7.add(tx12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 50));

        t17.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t17.setText("Address");
        jPanel7.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 880, 140));

        tx13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx13.setForeground(new java.awt.Color(102, 102, 102));
        tx13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx13ActionPerformed(evt);
            }
        });
        jPanel6.add(tx13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 60));

        t18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t18.setText("Address");
        jPanel6.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 30));

        tx14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx14.setForeground(new java.awt.Color(102, 102, 102));
        tx14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx14ActionPerformed(evt);
            }
        });
        jPanel6.add(tx14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 160, 30));

        t19.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t19.setText("State");
        jPanel6.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 60, 30));

        t20.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t20.setText("Pin Code");
        jPanel6.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 30));

        tx15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx15.setForeground(new java.awt.Color(102, 102, 102));
        tx15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx15ActionPerformed(evt);
            }
        });
        jPanel6.add(tx15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 230, 30));

        tx16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx16.setForeground(new java.awt.Color(102, 102, 102));
        tx16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx16ActionPerformed(evt);
            }
        });
        jPanel6.add(tx16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 880, 180));

        t21.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t21.setText("Pin Code");
        jPanel4.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 110, 30));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 860, 190));

        bot4.setBackground(new java.awt.Color(255, 255, 255));
        bot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        bot4.setText("+ Add Passanger");
        bot4.setColorHover(new java.awt.Color(255, 255, 255));
        bot4.setColorText(new java.awt.Color(0, 0, 0));
        bot4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot4ActionPerformed(evt);
            }
        });
        jPanel8.add(bot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 180, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx3.setForeground(new java.awt.Color(102, 102, 102));
        tx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3ActionPerformed(evt);
            }
        });
        jPanel3.add(tx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 360, 40));

        t7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t7.setText("Email Id");
        jPanel3.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 140, 30));

        t10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t10.setText("Phone Number");
        jPanel3.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        tx4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx4.setForeground(new java.awt.Color(102, 102, 102));
        tx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx4ActionPerformed(evt);
            }
        });
        jPanel3.add(tx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 40));

        jPanel8.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 800, 130));

        rSButtonHover1.setText("show passanger details");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 260, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Your Booking Date");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tx17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx17ActionPerformed(evt);
            }
        });
        jPanel8.add(tx17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Account");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, 20));

        rSMaterialButtonCircle3.setText("X");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel8.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 70, 40));

        rSMaterialButtonCircle4.setText("<--");
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanel8.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        String d=tx18.getText();
        String s=t1.getText();
        String u =tx19.getText();
        new showpassangerdetails(d,s,u).setVisible(true);

    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void tx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx4ActionPerformed

    private void tx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3ActionPerformed

    private void bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot4ActionPerformed
        // TODO add your handling code here:
        String unm,pnm,em,phn,add,gen,age,contry,cla,pin,po,city,state,fid;

        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");

            // String unm,pnm,em,phn,add,gen,age,contry,cla,pin,po,city,state,fid;
            unm=tx19.getText();
            pnm=tx1.getText();
            age=tx2.getText();
            em=tx3.getText();
            phn=tx4.getText();
            city=tx5.getText();
            add=tx7.getText();
            pin=tx8.getText();
            state=tx9.getText();
            po=tx10.getText();
            contry=c2.getSelectedItem().toString();
            gen=c1.getSelectedItem().toString();
            cla=c3.getSelectedItem().toString();
            fid=t1.getText();
            String sql="insert into Customer_AirLine(UserName,passanger_name,age,Email,Ph_no,class,Address,Gender,pin_code,state,post_office,country,city,flightid)values('"+unm+"','"+pnm+"','"+age+"','"+em+"','"+phn+"','"+cla+"','"+add+"','"+gen+"','"+pin+"','"+state+"','"+po+"','"+contry+"','"+city+"','"+fid+"')";

            pst=this.con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i==1)
            {
                JOptionPane.showConfirmDialog(null, "booking  Successfully , "+y+ " passenger Added!!!");

                tx1.setText("");
                tx2.setText("");

                y++;
            }
            else
            JOptionPane.showConfirmDialog(null, "booking  unSuccessfully !!!");
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_bot4ActionPerformed

    private void tx16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx16ActionPerformed

    private void tx15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx15ActionPerformed

    private void tx14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx14ActionPerformed

    private void tx13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx13ActionPerformed

    private void tx12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx12ActionPerformed

    private void tx11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx11ActionPerformed

    private void tx10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx10ActionPerformed

    private void tx9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx9ActionPerformed

    private void tx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx8ActionPerformed

    private void tx7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx7ActionPerformed

    private void tx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx6ActionPerformed

    private void tx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx5ActionPerformed

    private void tx18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx18ActionPerformed

    private void tx19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx19ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void tx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx2ActionPerformed

    private void tx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx1ActionPerformed

    private void tx17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx17ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        // TODO add your handling code here:
        new customer_flightpage(f).setVisible(true);      
        this.hide();
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flight_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flight_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flight_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flight_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flight_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover bot4;
    private rojerusan.RSComboMetro c1;
    private rojerusan.RSComboMetro c2;
    private rojerusan.RSComboMetro c3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JTextField tx1;
    private javax.swing.JTextField tx10;
    private javax.swing.JTextField tx11;
    private javax.swing.JTextField tx12;
    private javax.swing.JTextField tx13;
    private javax.swing.JTextField tx14;
    private javax.swing.JTextField tx15;
    private javax.swing.JTextField tx16;
    private rojeru_san.complementos.RSButtonHover tx17;
    private javax.swing.JTextField tx18;
    private javax.swing.JTextField tx19;
    private javax.swing.JTextField tx2;
    private javax.swing.JTextField tx3;
    private javax.swing.JTextField tx4;
    private javax.swing.JTextField tx5;
    private javax.swing.JTextField tx6;
    private javax.swing.JTextField tx7;
    private javax.swing.JTextField tx8;
    private javax.swing.JTextField tx9;
    // End of variables declaration//GEN-END:variables
}
