/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airline.reservation.system;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
/**
 *
 * @author GARGI GHOSH
 */
public class flight_details extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
PreparedStatement pst;
int j;
int id;

 int c=0;
    /**
     * Creates new form flight_details
     */
    public flight_details() {
        initComponents();
        
        try
        {
         text10.setVisible(false);
         tbl_flightdetils.removeColumn(tbl_flightdetils.getColumnModel().getColumn(9));

        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        String sql2;
        sql2 ="select * from flight_airline";
        stmt=this.con.createStatement();
        rs=stmt.executeQuery(sql2);
        while(rs.next())
        {
           c1.addItem(rs.getString("Source"));
           c2.addItem(rs.getString("Destination"));
           //c++;
        }
        }
        catch(Exception e)
        {
        
        }
    
    }
    

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorRoundRectangle2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorRoundRectangle2D();
        t3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        b1 = new rojerusan.RSMaterialButtonCircle();
        b2 = new rojerusan.RSMaterialButtonCircle();
        t2 = new javax.swing.JLabel();
        txt9 = new javax.swing.JTextField();
        t4 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        t7 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        t8 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        t11 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        bot4 = new rojerusan.RSMaterialButtonCircle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_flightdetils = new rojeru_san.complementos.RSTableMetro();
        c1 = new rojerusan.RSComboMetro();
        c2 = new rojerusan.RSComboMetro();
        show = new rojerusan.RSMaterialButtonCircle();
        bot2 = new rojerusan.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ca1 = new com.toedter.calendar.JDateChooser();

        t3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t3.setText("Enter The Airline No    ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setText("Add");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel4.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 110, 49));

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setText("Delete");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel4.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 110, 49));

        t2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t2.setText(" Price ");
        jPanel4.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 70, 40));

        txt9.setBackground(new java.awt.Color(51, 102, 255));
        txt9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });
        jPanel4.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 250, 40));

        t4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t4.setText("Enter The Airline No");
        jPanel4.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 160, 40));

        t5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t5.setText("Source ");
        jPanel4.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, 40));

        t6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t6.setText("Destination");
        jPanel4.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 40));

        txt1.setBackground(new java.awt.Color(51, 102, 255));
        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel4.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 300, 40));

        txt2.setBackground(new java.awt.Color(51, 102, 255));
        txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        jPanel4.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 300, 40));

        txt3.setBackground(new java.awt.Color(51, 102, 255));
        txt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        jPanel4.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 300, 40));

        txt4.setBackground(new java.awt.Color(51, 102, 255));
        txt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        jPanel4.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 300, 40));

        t7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t7.setText(" Departure Date");
        jPanel4.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 140, 40));

        txt5.setBackground(new java.awt.Color(51, 102, 255));
        txt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        jPanel4.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 170, 40));

        t8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t8.setText("Arrival Time");
        jPanel4.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 110, 40));

        txt8.setBackground(new java.awt.Color(51, 102, 255));
        txt8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        jPanel4.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/money.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 40, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/Airplane-icon.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/flight no img.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/icons8-travel-diary-48.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/icons8-travel-diary-48.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/time.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 40, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/time.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, 50));

        t9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t9.setText("Enter The Flight No");
        jPanel4.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 160, 40));

        t10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t10.setText("Departure Time");
        jPanel4.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 140, 40));

        txt6.setBackground(new java.awt.Color(51, 102, 255));
        txt6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        jPanel4.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 40));

        t11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t11.setText("Arrival Date");
        jPanel4.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 110, 40));

        txt7.setBackground(new java.awt.Color(51, 102, 255));
        txt7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        jPanel4.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 200, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/time.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 40, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flight details img/time.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 40, 50));

        text10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text10ActionPerformed(evt);
            }
        });
        jPanel4.add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 30, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonCircle3.setText("X");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 70, 40));

        bot4.setText("<--");
        bot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot4ActionPerformed(evt);
            }
        });
        jPanel1.add(bot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 40));

        tbl_flightdetils.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline_No", "Flight_No", "Source", "Destination", "Departure Date", "Departure time", "Arrival Date", "Arrival time", "Price", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_flightdetils.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_flightdetils.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_flightdetils.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_flightdetils.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_flightdetils.setMinimumSize(new java.awt.Dimension(2147483647, 0));
        tbl_flightdetils.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_flightdetilsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_flightdetils);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 1030, 320));

        c1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        c1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, 40));

        c2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        c2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 220, 40));

        show.setBackground(new java.awt.Color(255, 51, 51));
        show.setForeground(new java.awt.Color(0, 0, 0));
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 120, 50));

        bot2.setBackground(new java.awt.Color(255, 51, 51));
        bot2.setForeground(new java.awt.Color(0, 0, 0));
        bot2.setText("Refresh Table");
        bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot2ActionPerformed(evt);
            }
        });
        jPanel1.add(bot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 210, 50));

        jLabel1.setFont(new java.awt.Font("NSimSun", 0, 48)); // NOI18N
        jLabel1.setText("Flights ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 50));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 48)); // NOI18N
        jLabel2.setText("Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 170, 60));

        ca1.setBackground(new java.awt.Color(51, 102, 255));
        ca1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(51, 102, 255)));
        ca1.setForeground(new java.awt.Color(51, 102, 255));
        ca1.setDateFormatString("dd-MM-yy");
        ca1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(ca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 1100, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
       try
     {
       String ano,fno,src,destn,atym,dtym,price,ddate,adate,id;
       SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
       String dt1=sdf.format(ca1.getDate());
       Class.forName("com.mysql.cj.jdbc.Driver");
        
        System.out.println(dt1);
       con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
       String sql="select * from flight_airline where Source='"+c1.getSelectedItem()+"' and Destination ='"+c2.getSelectedItem()+"' and Departure_date ='"+dt1+"'";
       stmt=con.createStatement();
       rs=stmt.executeQuery(sql);
       while(rs.next())
       {
           
         ano=rs.getString("Airline_No");
         fno=rs.getString("Flight_No");
         src=rs.getString("Source");
         destn=rs.getString("Destination");
         ddate=rs.getString("Departure_date");
         dtym=rs.getString("Departure_time");
         adate=rs.getString("Arrival_date");
         atym=rs.getString("Arrival_Time");
         price=rs.getString("price");
         id=rs.getString("ID");
         
         String arr[]={ano,fno,src,destn,ddate,dtym,adate,atym,price,id};
         DefaultTableModel ob=(DefaultTableModel)tbl_flightdetils.getModel();
         ob.addRow(arr);
         
         //t1.append(ano+"\t");
         //t1.append(fno+"\n");
       }
     }
     catch(Exception e)
     {
     System.out.print(e);
     }
      
       
    }//GEN-LAST:event_showActionPerformed

    private void bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel ob=(DefaultTableModel)tbl_flightdetils.getModel();
    c=ob.getRowCount();
    //System.out.print(c);
    for(int i=c-1;i>=0;i--)
        ob.removeRow(i);
    }//GEN-LAST:event_bot2ActionPerformed

    private void bot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot4ActionPerformed
        // TODO add your handling code here:
        admin_indexpage obn =  new admin_indexpage();
        this.hide();
        obn.show();
    }//GEN-LAST:event_bot4ActionPerformed

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try
        {
       String ano,fno,src,destn,atym,dtym,price,ddate,adate,id;
        
      Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        fno=txt1.getText();
        ano=txt2.getText();
        src=txt3.getText();
        destn=txt4.getText();
        ddate=txt5.getText();
        dtym=txt6.getText();
        adate=txt7.getText();
        atym=txt8.getText();
        price=txt9.getText();
        id=text10.getText();
       //String sql2="select * from flight_airline";
       //stmt=con.createStatement();
      // rs=stmt.executeQuery(sql2);
       //while(rs.next())
      // {
          // id=rs.getInt(id);
       //} 
        //System.out.print(id);
      String sql="delete from flight_airline where id='"+id+"'";     
      pst=this.con.prepareStatement(sql);
       int i=pst.executeUpdate();
       if(i==1)
       {
        JOptionPane.showConfirmDialog(null, "Deleted Successfully !!!");
       DefaultTableModel obf=(DefaultTableModel)tbl_flightdetils.getModel();
       c=obf.getRowCount();
       //System.out.print(c);
       for( j=c-1;j>=0;j--);
       {
        obf.removeRow(j);
       }         
          /*try
          {
          
       Class.forName("com.mysql.cj.jdbc.Driver");
       con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
       String sql2="select * from flight_airline";
       stmt=con.createStatement();
       rs=stmt.executeQuery(sql2);
        
         ano=rs.getString("Airline_No");
         fno=rs.getString("Flight_No");
         src=rs.getString("Source");
         destn=rs.getString("Destination");
         ddate=rs.getString("Departure_date");
         dtym=rs.getString("Departure_time");
         adate=rs.getString("Arrival_date");
         atym=rs.getString("Arrival_Time");
         price=rs.getString("price");
         String arr[]={ano,fno,src,destn,ddate,dtym,adate,atym,price};
         DefaultTableModel ob=(DefaultTableModel)tbl_flightdetils.getModel();
         ob.addRow(arr);
         
 
          }
        catch(Exception e)
                {
                System.out.print(e);
                }
         
         //t1.append(ano+"\t");
         //t1.append(fno+"\n");
       

       }
      else
          JOptionPane.showConfirmDialog(null, "Deleted unSuccessfully !!!");
      */

        } 
       else
            JOptionPane.showConfirmDialog(null, "Deleted unSuccessfull !!!");

        }
        catch(Exception e)
        {
            System.out.print(e);
        }
            
                // TODO add your handling code here:
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
       String ano,fno,src,destn,atym,dtym,price,ddate,adate;
        
      Class.forName("com.mysql.cj.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
        fno=txt1.getText();
        ano=txt2.getText();
        src=txt3.getText();
        destn=txt4.getText();
        ddate=txt5.getText();
        dtym=txt6.getText();
        adate=txt7.getText();
        atym=txt8.getText();
        price=txt9.getText();
      String sql="insert into flight_airline(Airline_No,Flight_No,Source,Destination,Departure_time,Arrival_Time,Price,Departure_date,Arrival_date)values('"+fno+"','"+ano+"','"+src+"','"+destn+"','"+dtym+"','"+atym+"','"+price+"','"+ddate+"','"+adate+"')";     
      pst=this.con.prepareStatement(sql);
       int i=pst.executeUpdate();
       if(i==1)
       {
          JOptionPane.showConfirmDialog(null, "Inserted Successfully !!!");
       DefaultTableModel obf=(DefaultTableModel)tbl_flightdetils.getModel();
       c=obf.getRowCount();
       //System.out.print(c);
       for( j=c-1;j>=0;j--);
       {
        obf.removeRow(j);
       }         
          try
          {
          
       Class.forName("com.mysql.cj.jdbc.Driver");
       con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline_reservation_system?useSSL=false","root","root");
       String sql2="select * from flight_airline where Flight_NO='"+txt2.getText()+"'";
       stmt=con.createStatement();
       rs=stmt.executeQuery(sql2);
        while(rs.next())
       {
           
         ano=rs.getString("Airline_No");
         fno=rs.getString("Flight_No");
         src=rs.getString("Source");
         destn=rs.getString("Destination");
         dtym=rs.getString("Departure_time");
         atym=rs.getString("Arrival_Time");
         price=rs.getString("price");
         String arr[]={ano,fno,src,destn,dtym,atym,price};
         DefaultTableModel ob=(DefaultTableModel)tbl_flightdetils.getModel();
         ob.addRow(arr);
       }
          }
        catch(Exception e)
                {
                System.out.print(e);
                }
         
         //t1.append(ano+"\t");
         //t1.append(fno+"\n");
       

       }
      else
          JOptionPane.showConfirmDialog(null, "Inserted unSuccessfully !!!");
      

        }
        catch(Exception e)
        {
            System.out.print(e);
        }
            
        
    }//GEN-LAST:event_b1ActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    private void tbl_flightdetilsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_flightdetilsMouseClicked
        // TODO add your handling code here:
        int rowno=tbl_flightdetils.getSelectedRow();
        TableModel model=tbl_flightdetils.getModel();
        text10.setVisible(false);
        txt1.setText(model.getValueAt(rowno, 0).toString());
        txt2.setText(model.getValueAt(rowno, 1).toString());
        txt3.setText(model.getValueAt(rowno, 2).toString());
        txt4.setText(model.getValueAt(rowno, 3).toString());
        txt5.setText(model.getValueAt(rowno, 4).toString());
        txt6.setText(model.getValueAt(rowno, 5).toString());
        txt7.setText(model.getValueAt(rowno, 6).toString());
        txt8.setText(model.getValueAt(rowno, 7).toString());
        txt9.setText(model.getValueAt(rowno, 8).toString());
        text10.setText(model.getValueAt(rowno,9).toString());


        
    }//GEN-LAST:event_tbl_flightdetilsMouseClicked

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void text10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text10ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flight_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flight_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flight_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flight_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flight_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle b1;
    private rojerusan.RSMaterialButtonCircle b2;
    private rojerusan.RSMaterialButtonCircle bot2;
    private rojerusan.RSMaterialButtonCircle bot4;
    private rojerusan.RSComboMetro c1;
    private rojerusan.RSComboMetro c2;
    private com.toedter.calendar.JDateChooser ca1;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorRoundRectangle2D evaluatorRoundRectangle2D1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle show;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    private rojeru_san.complementos.RSTableMetro tbl_flightdetils;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
