/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;
import java.awt.Color;
import java.awt.*;
import javax.swing.JFrame;  
/**
 *
 * @author GARGI GHOSH
 */
public class homepage extends javax.swing.JFrame {
      
    /**
     * Creates new form homepage
     */
    
    
     
    public homepage() {
        initComponents();
        //initialize();
      //getContentPane().setBackground(Color.magenta);
       Color col =new Color(227, 236, 252);
       getContentPane().setBackground(col);
    }
    
   
    //public void initialize()
    //{
        
        
    
   // class  extends j1
   // {
        
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        te2 = new rojerusan.RSMaterialButtonRectangle();
        te1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setBackground(new java.awt.Color(51, 102, 255));
        j1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Airline");
        j1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 92, 163, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel2.setText("Resevation ");
        j1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 175, 269, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel3.setText("System");
        j1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 264, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plane.png"))); // NOI18N
        j1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 170, 130));

        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 520));

        te2.setText("Admin Login");
        te2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te2ActionPerformed(evt);
            }
        });
        getContentPane().add(te2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 230, 82));

        te1.setText("User Login");
        te1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te1ActionPerformed(evt);
            }
        });
        getContentPane().add(te1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 220, 80));

        rSMaterialButtonCircle1.setText("x");
        rSMaterialButtonCircle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle1MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pl.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, 660, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void te1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te1ActionPerformed
        // TODO add your handling code here:
        
        login_page obj = new login_page();
        this.hide();
        obj.show();
    }//GEN-LAST:event_te1ActionPerformed

    private void te2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te2ActionPerformed
        // TODO add your handling code here:
        admin_loginpage ob= new admin_loginpage();
        this.hide();
        ob.show();
    }//GEN-LAST:event_te2ActionPerformed

    private void rSMaterialButtonCircle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonCircle1MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       // Frame f = new Frame();
       // f.setTitle("Airline Reservation Sytem");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          //Frame f = new Frame();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
            
           

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel j1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonRectangle te1;
    private rojerusan.RSMaterialButtonRectangle te2;
    // End of variables declaration//GEN-END:variables
}
