/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

/**
 *
 * @author GARGI GHOSH
 */
public class panel1 extends javax.swing.JFrame {

    /**
     * Creates new form panel1
     */
    public panel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        tx1 = new javax.swing.JTextField();
        c3 = new rojerusan.RSComboMetro();
        bot3 = new rojeru_san.complementos.RSButtonHover();
        tx2 = new javax.swing.JTextField();
        c1 = new rojerusan.RSComboMetro();
        c2 = new rojerusan.RSComboMetro();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t2.setText("Class");
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 50, 30));

        t3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t3.setText("Passenger Name");
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        t4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t4.setText("Gender");
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 70, 30));

        tx1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx1.setForeground(new java.awt.Color(102, 102, 102));
        tx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx1ActionPerformed(evt);
            }
        });
        jPanel2.add(tx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        c3.setForeground(new java.awt.Color(51, 51, 51));
        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First Class", "Business Class", "Economy Class" }));
        jPanel2.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 170, 30));

        bot3.setBackground(new java.awt.Color(255, 255, 255));
        bot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        bot3.setText("+ Add Passanger");
        bot3.setColorHover(new java.awt.Color(255, 255, 255));
        bot3.setColorText(new java.awt.Color(0, 0, 0));
        bot3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        bot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot3ActionPerformed(evt);
            }
        });
        jPanel2.add(bot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 20));

        tx2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tx2.setForeground(new java.awt.Color(102, 102, 102));
        tx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx2ActionPerformed(evt);
            }
        });
        jPanel2.add(tx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 50, 30));

        c1.setForeground(new java.awt.Color(51, 51, 51));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Transgender" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 120, -1));

        c2.setForeground(new java.awt.Color(51, 51, 51));
        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afghanistan", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "India", "Indonesia" }));
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 210, 30));

        t5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t5.setText("Age");
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 50, 30));

        t6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        t6.setText("Country");
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 90, 30));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(204, 204, 204));
        rSMaterialButtonCircle1.setForeground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonCircle1.setText("X");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 50, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx1ActionPerformed

    private void bot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bot3ActionPerformed

    private void tx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover bot3;
    private rojerusan.RSComboMetro c1;
    private rojerusan.RSComboMetro c2;
    private rojerusan.RSComboMetro c3;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JTextField tx1;
    private javax.swing.JTextField tx2;
    // End of variables declaration//GEN-END:variables
}
